# Generated by Django 3.1.1 on 2023-10-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0005_cheese_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='firmness',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
