# Generated by Django 3.1.1 on 2023-10-12 18:33

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0007_auto_20231011_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheese',
            name='rating',
        ),
        migrations.AlterField(
            model_name='cheese',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Cheese Address'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='cheese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheeses.cheese'),
        ),
    ]
