# Generated by Django 3.1.1 on 2023-10-12 21:22

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0008_auto_20231012_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True, verbose_name='Cheese Address'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='cheese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='cheeses.cheese'),
        ),
    ]
